import { relative, sep } from "node:path";
import type { FileEntry } from "./scanner.js";

export type OutputFormat = "markdown" | "xml" | "plain";

const LANG_MAP: Record<string, string> = {
  ".ts": "typescript",
  ".tsx": "tsx",
  ".js": "javascript",
  ".jsx": "jsx",
  ".py": "python",
  ".rb": "ruby",
  ".rs": "rust",
  ".go": "go",
  ".java": "java",
  ".kt": "kotlin",
  ".swift": "swift",
  ".c": "c",
  ".cpp": "cpp",
  ".h": "c",
  ".css": "css",
  ".scss": "scss",
  ".html": "html",
  ".vue": "vue",
  ".svelte": "svelte",
  ".json": "json",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".toml": "toml",
  ".md": "markdown",
  ".sh": "bash",
  ".bash": "bash",
  ".sql": "sql",
  ".graphql": "graphql",
  ".xml": "xml",
  ".tf": "hcl",
  ".lua": "lua",
  ".zig": "zig",
  ".prisma": "prisma",
  ".proto": "protobuf",
};

function getLang(ext: string): string {
  return LANG_MAP[ext] ?? "";
}

function formatMarkdown(
  files: FileEntry[],
  rootDir: string,
): string {
  const parts: string[] = [];
  parts.push(`# Codebase Prompt\n`);
  parts.push(`> Generated by promptpack | ${files.length} files\n`);

  parts.push(`## File Tree\n`);
  parts.push("```");
  for (const file of files) {
    const rel = relative(rootDir, file.path).split(sep).join("/");
    parts.push(rel);
  }
  parts.push("```\n");

  parts.push(`## Files\n`);
  for (const file of files) {
    const rel = relative(rootDir, file.path).split(sep).join("/");
    const lang = getLang(file.extension);
    parts.push(`### ${rel}\n`);
    parts.push(`\`\`\`${lang}`);
    parts.push(file.content.trimEnd());
    parts.push("```\n");
  }

  return parts.join("\n");
}

function formatXml(
  files: FileEntry[],
  rootDir: string,
): string {
  const parts: string[] = [];
  parts.push("<codebase>");
  parts.push(`  <meta files="${files.length}" generator="promptpack" />`);

  for (const file of files) {
    const rel = relative(rootDir, file.path).split(sep).join("/");
    parts.push(`  <file path="${rel}">`);
    parts.push(file.content.trimEnd());
    parts.push("  </file>");
  }

  parts.push("</codebase>");
  return parts.join("\n");
}

function formatPlain(
  files: FileEntry[],
  rootDir: string,
): string {
  const parts: string[] = [];
  parts.push(`Codebase Prompt (${files.length} files)\n`);
  parts.push("=".repeat(60) + "\n");

  for (const file of files) {
    const rel = relative(rootDir, file.path).split(sep).join("/");
    parts.push(`--- ${rel} ---`);
    parts.push(file.content.trimEnd());
    parts.push("");
  }

  return parts.join("\n");
}

export function formatOutput(
  files: FileEntry[],
  rootDir: string,
  format: OutputFormat,
): string {
  switch (format) {
    case "markdown":
      return formatMarkdown(files, rootDir);
    case "xml":
      return formatXml(files, rootDir);
    case "plain":
      return formatPlain(files, rootDir);
  }
}
